! ================================================================
! 
!> @note
!! This software was developed at the National Institute of
!! Standards and Technology by employees of the Federal Government
!! in the course of their official duties.  Pursuant to Title 17
!! Section 105 of the United States Code, this software is not
!! subject to copyright protection and is in the public domain.
!! This software is an experimental system.  NIST assumes no
!! responsibility whatsoever for its use by other parties, and makes
!! no guarantees, expressed or implied, about its quality,
!! reliability, or any other characteristic.  We would appreciate
!! acknowledgment if the software is used.
! 
! ================================================================
!
!> @file
!! This file defines the `zeno_codes_data` module declares data members
!! that used to be in `/morse/` common block.  These data members are
!! global constants that correspond to ZENO command names.  They are
!! used in various routines to test the *type* of an element.
!! 
!! @defgroup zeno_codes_data Codes of Command Keywords
!! 
!! Defines integer constants that correspond to ZENO command names.
!! 
!! @details
!! The module defines integer constants that correspond to ZENO command
!! names and that are used in various routines to test the *type* of an
!! element.
!! 
!! @warning there are too many variables to list individually.  Should
!! use equivalent of C/C++ `enums`.  Parsing code should be
!! automatically generated via the likes of `flex` and `bison`.
!!
!! @todo Replace by an `enum` type.  The list of **keywords** should be
!! automatically generated by the likes of `flex` and `bison`.
!! 
!! @author Mark Mansfield (formerly of Stevens Institute) and students
!! @author Walid Keyrouz (walid.keyrouz@nist.gov)
!! @date   Mon Dec 23 17:44:46 2013 EST
!
! Time-stamp: <2015-01-07 11:57:01 walid>
! 
! ================================================================

module zeno_codes_data

  !! ================================================================

  implicit none

  public

  !!  Map a unique integer to each one of these variables:

  integer, parameter :: sphere_code         =  333
  integer, parameter :: triangle_code       =  369
  integer, parameter :: disk_code           =  140
  integer, parameter :: open_cylinder_code  =  -45
  integer, parameter :: solid_cylinder_code =   45
  integer, parameter :: donut_code          =  314
  integer, parameter :: ellipsoid_code      =   95
  integer, parameter :: cube_code           =   66
  integer, parameter :: pillar_code         =  111
  integer, parameter :: skin_code           =   39
  integer, parameter :: units_code          =   99
  integer, parameter :: hunits_code         =  100
  integer, parameter :: meter_code          =  101
  integer, parameter :: cm_code             =  102
  integer, parameter :: nm_code             =  103
  integer, parameter :: angstrom_code       = -100
  integer, parameter :: length_code         = -101
  integer, parameter :: temp_code           = -102
  integer, parameter :: celcius_code        = -103
  integer, parameter :: kelvin_code         =  273
  integer, parameter :: mass_code           =  200
  integer, parameter :: da_code             =  201
  integer, parameter :: kda_code            =  202
  integer, parameter :: gram_code           =  203
  integer, parameter :: kg_code             =  204
  integer, parameter :: visc_code           =  210
  integer, parameter :: poise_code          = -210
  integer, parameter :: cp_code             =  211
  integer, parameter :: solvent_code        = -211
  integer, parameter :: water_code          =  212
  integer, parameter :: rlaunch_code        =  213
  integer, parameter :: bf_code             =  1096

  !! ================================================================

end module zeno_codes_data

!!! ================================================================

!!! Local Variables:
!!! mode: f90
!!! time-stamp-line-limit: 30
!!! fill-column: 72
!!! End:
