/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  /usr/bin/gengetopt -i ./options.ggo --conf-parser --set-version=5.3.0 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: zeno [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -c, --config-file=STRING      Config file name",
  "  -i, --input-file=STRING       Input file name",
  "      --csv-output-file=STRING  Write output in CSV format to the specified\n                                  file in addition to displaying the regular\n                                  output",
  "      --num-walks=LONGLONG      Number of walk-on-spheres walks to perform.\n                                  Fewer walks may be performed if another\n                                  stopping condition is reached first",
  "      --num-interior-samples=LONGLONG\n                                Number of interior samples to take.  Fewer\n                                  samples may be taken if another stopping\n                                  condition is reached first",
  "      --max-rsd-capacitance=DOUBLE\n                                Perform walk-on-spheres walks until the\n                                  relative standard deviation of the\n                                  capacitance drops below this value.  This\n                                  value may not be reached if another stopping\n                                  condition is reached first.  Relative\n                                  standard deviation is defined as\n                                  (Standard_Deviation/Mean)*100%",
  "      --max-rsd-polarizability=DOUBLE\n                                Perform walk-on-spheres walks until the\n                                  relative standard deviation of the mean\n                                  electric polarizability drops below this\n                                  value. This value may not be reached if\n                                  another stopping condition is reached first.\n                                  Relative standard deviation is defined as\n                                  (Standard_Deviation/Mean)*100%",
  "      --max-rsd-volume=DOUBLE   Take interior samples until the relative\n                                  standard deviation of volume drops below this\n                                  value.  This value may not be reached if\n                                  another stopping condition is reached first.\n                                  Relative standard deviation is defined as\n                                  (Standard_Deviation/Mean)*100%",
  "      --min-num-walks=LONGLONG  Minimum number of walk-on-spheres walks to\n                                  perform when using max-rsd stopping\n                                  conditions  (default=`1000')",
  "      --min-num-interior-samples=LONGLONG\n                                Minimum number of interior samples to take when\n                                  using max-rsd stopping conditions\n                                  (default=`10000')",
  "      --max-run-time=DOUBLE     Max time (in seconds) that the program is\n                                  allowed to run.  If this time is reached, the\n                                  computation will be stopped and the results\n                                  computed so far will be displayed",
  "      --num-threads=INT         Number of threads to use  (default=Number of\n                                  logical cores)",
  "      --seed=INT                Seed for the random number generator\n                                  (default=Randomly set)",
  "      --surface-points-file=STRING\n                                Name of file for writing the surface points\n                                  from Walk-on-Spheres",
  "      --interior-points-file=STRING\n                                Name of file for writing the interior sample\n                                  points",
  "      --print-counts            Print statistics related to counts of hit\n                                  points",
  "      --print-benchmarks        Print detailed RAM and timing information",
  "      --virial-steps=LONGLONG   Number of Monte Carlo steps to perform to\n                                  compute a virial coefficient",
  "      --virial-coefficient-order=INT\n                                Order of virial coefficient to compute",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_DOUBLE
  , ARG_LONGLONG
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->config_file_given = 0 ;
  args_info->input_file_given = 0 ;
  args_info->csv_output_file_given = 0 ;
  args_info->num_walks_given = 0 ;
  args_info->num_interior_samples_given = 0 ;
  args_info->max_rsd_capacitance_given = 0 ;
  args_info->max_rsd_polarizability_given = 0 ;
  args_info->max_rsd_volume_given = 0 ;
  args_info->min_num_walks_given = 0 ;
  args_info->min_num_interior_samples_given = 0 ;
  args_info->max_run_time_given = 0 ;
  args_info->num_threads_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->surface_points_file_given = 0 ;
  args_info->interior_points_file_given = 0 ;
  args_info->print_counts_given = 0 ;
  args_info->print_benchmarks_given = 0 ;
  args_info->virial_steps_given = 0 ;
  args_info->virial_coefficient_order_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->config_file_arg = NULL;
  args_info->config_file_orig = NULL;
  args_info->input_file_arg = NULL;
  args_info->input_file_orig = NULL;
  args_info->csv_output_file_arg = NULL;
  args_info->csv_output_file_orig = NULL;
  args_info->num_walks_orig = NULL;
  args_info->num_interior_samples_orig = NULL;
  args_info->max_rsd_capacitance_orig = NULL;
  args_info->max_rsd_polarizability_orig = NULL;
  args_info->max_rsd_volume_orig = NULL;
  args_info->min_num_walks_arg = 1000;
  args_info->min_num_walks_orig = NULL;
  args_info->min_num_interior_samples_arg = 10000;
  args_info->min_num_interior_samples_orig = NULL;
  args_info->max_run_time_orig = NULL;
  args_info->num_threads_orig = NULL;
  args_info->seed_orig = NULL;
  args_info->surface_points_file_arg = NULL;
  args_info->surface_points_file_orig = NULL;
  args_info->interior_points_file_arg = NULL;
  args_info->interior_points_file_orig = NULL;
  args_info->virial_steps_orig = NULL;
  args_info->virial_coefficient_order_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->config_file_help = gengetopt_args_info_help[2] ;
  args_info->input_file_help = gengetopt_args_info_help[3] ;
  args_info->csv_output_file_help = gengetopt_args_info_help[4] ;
  args_info->num_walks_help = gengetopt_args_info_help[5] ;
  args_info->num_interior_samples_help = gengetopt_args_info_help[6] ;
  args_info->max_rsd_capacitance_help = gengetopt_args_info_help[7] ;
  args_info->max_rsd_polarizability_help = gengetopt_args_info_help[8] ;
  args_info->max_rsd_volume_help = gengetopt_args_info_help[9] ;
  args_info->min_num_walks_help = gengetopt_args_info_help[10] ;
  args_info->min_num_interior_samples_help = gengetopt_args_info_help[11] ;
  args_info->max_run_time_help = gengetopt_args_info_help[12] ;
  args_info->num_threads_help = gengetopt_args_info_help[13] ;
  args_info->seed_help = gengetopt_args_info_help[14] ;
  args_info->surface_points_file_help = gengetopt_args_info_help[15] ;
  args_info->interior_points_file_help = gengetopt_args_info_help[16] ;
  args_info->print_counts_help = gengetopt_args_info_help[17] ;
  args_info->print_benchmarks_help = gengetopt_args_info_help[18] ;
  args_info->virial_steps_help = gengetopt_args_info_help[19] ;
  args_info->virial_coefficient_order_help = gengetopt_args_info_help[20] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->config_file_arg));
  free_string_field (&(args_info->config_file_orig));
  free_string_field (&(args_info->input_file_arg));
  free_string_field (&(args_info->input_file_orig));
  free_string_field (&(args_info->csv_output_file_arg));
  free_string_field (&(args_info->csv_output_file_orig));
  free_string_field (&(args_info->num_walks_orig));
  free_string_field (&(args_info->num_interior_samples_orig));
  free_string_field (&(args_info->max_rsd_capacitance_orig));
  free_string_field (&(args_info->max_rsd_polarizability_orig));
  free_string_field (&(args_info->max_rsd_volume_orig));
  free_string_field (&(args_info->min_num_walks_orig));
  free_string_field (&(args_info->min_num_interior_samples_orig));
  free_string_field (&(args_info->max_run_time_orig));
  free_string_field (&(args_info->num_threads_orig));
  free_string_field (&(args_info->seed_orig));
  free_string_field (&(args_info->surface_points_file_arg));
  free_string_field (&(args_info->surface_points_file_orig));
  free_string_field (&(args_info->interior_points_file_arg));
  free_string_field (&(args_info->interior_points_file_orig));
  free_string_field (&(args_info->virial_steps_orig));
  free_string_field (&(args_info->virial_coefficient_order_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->config_file_given)
    write_into_file(outfile, "config-file", args_info->config_file_orig, 0);
  if (args_info->input_file_given)
    write_into_file(outfile, "input-file", args_info->input_file_orig, 0);
  if (args_info->csv_output_file_given)
    write_into_file(outfile, "csv-output-file", args_info->csv_output_file_orig, 0);
  if (args_info->num_walks_given)
    write_into_file(outfile, "num-walks", args_info->num_walks_orig, 0);
  if (args_info->num_interior_samples_given)
    write_into_file(outfile, "num-interior-samples", args_info->num_interior_samples_orig, 0);
  if (args_info->max_rsd_capacitance_given)
    write_into_file(outfile, "max-rsd-capacitance", args_info->max_rsd_capacitance_orig, 0);
  if (args_info->max_rsd_polarizability_given)
    write_into_file(outfile, "max-rsd-polarizability", args_info->max_rsd_polarizability_orig, 0);
  if (args_info->max_rsd_volume_given)
    write_into_file(outfile, "max-rsd-volume", args_info->max_rsd_volume_orig, 0);
  if (args_info->min_num_walks_given)
    write_into_file(outfile, "min-num-walks", args_info->min_num_walks_orig, 0);
  if (args_info->min_num_interior_samples_given)
    write_into_file(outfile, "min-num-interior-samples", args_info->min_num_interior_samples_orig, 0);
  if (args_info->max_run_time_given)
    write_into_file(outfile, "max-run-time", args_info->max_run_time_orig, 0);
  if (args_info->num_threads_given)
    write_into_file(outfile, "num-threads", args_info->num_threads_orig, 0);
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  if (args_info->surface_points_file_given)
    write_into_file(outfile, "surface-points-file", args_info->surface_points_file_orig, 0);
  if (args_info->interior_points_file_given)
    write_into_file(outfile, "interior-points-file", args_info->interior_points_file_orig, 0);
  if (args_info->print_counts_given)
    write_into_file(outfile, "print-counts", 0, 0 );
  if (args_info->print_benchmarks_given)
    write_into_file(outfile, "print-benchmarks", 0, 0 );
  if (args_info->virial_steps_given)
    write_into_file(outfile, "virial-steps", args_info->virial_steps_orig, 0);
  if (args_info->virial_coefficient_order_given)
    write_into_file(outfile, "virial-coefficient-order", args_info->virial_coefficient_order_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->input_file_given)
    {
      fprintf (stderr, "%s: '--input-file' ('-i') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    if (val) *((long long int*)field) = (long long int) strtoll (val, &stop_char, 0);
#else
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
#endif
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_DOUBLE:
  case ARG_LONGLONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "config-file",	1, NULL, 'c' },
        { "input-file",	1, NULL, 'i' },
        { "csv-output-file",	1, NULL, 0 },
        { "num-walks",	1, NULL, 0 },
        { "num-interior-samples",	1, NULL, 0 },
        { "max-rsd-capacitance",	1, NULL, 0 },
        { "max-rsd-polarizability",	1, NULL, 0 },
        { "max-rsd-volume",	1, NULL, 0 },
        { "min-num-walks",	1, NULL, 0 },
        { "min-num-interior-samples",	1, NULL, 0 },
        { "max-run-time",	1, NULL, 0 },
        { "num-threads",	1, NULL, 0 },
        { "seed",	1, NULL, 0 },
        { "surface-points-file",	1, NULL, 0 },
        { "interior-points-file",	1, NULL, 0 },
        { "print-counts",	0, NULL, 0 },
        { "print-benchmarks",	0, NULL, 0 },
        { "virial-steps",	1, NULL, 0 },
        { "virial-coefficient-order",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVc:i:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'c':	/* Config file name.  */
        
        
          if (update_arg( (void *)&(args_info->config_file_arg), 
               &(args_info->config_file_orig), &(args_info->config_file_given),
              &(local_args_info.config_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "config-file", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'i':	/* Input file name.  */
        
        
          if (update_arg( (void *)&(args_info->input_file_arg), 
               &(args_info->input_file_orig), &(args_info->input_file_given),
              &(local_args_info.input_file_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input-file", 'i',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Write output in CSV format to the specified file in addition to displaying the regular output.  */
          if (strcmp (long_options[option_index].name, "csv-output-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->csv_output_file_arg), 
                 &(args_info->csv_output_file_orig), &(args_info->csv_output_file_given),
                &(local_args_info.csv_output_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "csv-output-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of walk-on-spheres walks to perform.  Fewer walks may be performed if another stopping condition is reached first.  */
          else if (strcmp (long_options[option_index].name, "num-walks") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_walks_arg), 
                 &(args_info->num_walks_orig), &(args_info->num_walks_given),
                &(local_args_info.num_walks_given), optarg, 0, 0, ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "num-walks", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of interior samples to take.  Fewer samples may be taken if another stopping condition is reached first.  */
          else if (strcmp (long_options[option_index].name, "num-interior-samples") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_interior_samples_arg), 
                 &(args_info->num_interior_samples_orig), &(args_info->num_interior_samples_given),
                &(local_args_info.num_interior_samples_given), optarg, 0, 0, ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "num-interior-samples", '-',
                additional_error))
              goto failure;
          
          }
          /* Perform walk-on-spheres walks until the relative standard deviation of the capacitance drops below this value.  This value may not be reached if another stopping condition is reached first.  Relative standard deviation is defined as (Standard_Deviation/Mean)*100%.  */
          else if (strcmp (long_options[option_index].name, "max-rsd-capacitance") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->max_rsd_capacitance_arg), 
                 &(args_info->max_rsd_capacitance_orig), &(args_info->max_rsd_capacitance_given),
                &(local_args_info.max_rsd_capacitance_given), optarg, 0, 0, ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "max-rsd-capacitance", '-',
                additional_error))
              goto failure;
          
          }
          /* Perform walk-on-spheres walks until the relative standard deviation of the mean electric polarizability drops below this value. This value may not be reached if another stopping condition is reached first. Relative standard deviation is defined as (Standard_Deviation/Mean)*100%.  */
          else if (strcmp (long_options[option_index].name, "max-rsd-polarizability") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->max_rsd_polarizability_arg), 
                 &(args_info->max_rsd_polarizability_orig), &(args_info->max_rsd_polarizability_given),
                &(local_args_info.max_rsd_polarizability_given), optarg, 0, 0, ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "max-rsd-polarizability", '-',
                additional_error))
              goto failure;
          
          }
          /* Take interior samples until the relative standard deviation of volume drops below this value.  This value may not be reached if another stopping condition is reached first.  Relative standard deviation is defined as (Standard_Deviation/Mean)*100%.  */
          else if (strcmp (long_options[option_index].name, "max-rsd-volume") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->max_rsd_volume_arg), 
                 &(args_info->max_rsd_volume_orig), &(args_info->max_rsd_volume_given),
                &(local_args_info.max_rsd_volume_given), optarg, 0, 0, ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "max-rsd-volume", '-',
                additional_error))
              goto failure;
          
          }
          /* Minimum number of walk-on-spheres walks to perform when using max-rsd stopping conditions.  */
          else if (strcmp (long_options[option_index].name, "min-num-walks") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->min_num_walks_arg), 
                 &(args_info->min_num_walks_orig), &(args_info->min_num_walks_given),
                &(local_args_info.min_num_walks_given), optarg, 0, "1000", ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "min-num-walks", '-',
                additional_error))
              goto failure;
          
          }
          /* Minimum number of interior samples to take when using max-rsd stopping conditions.  */
          else if (strcmp (long_options[option_index].name, "min-num-interior-samples") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->min_num_interior_samples_arg), 
                 &(args_info->min_num_interior_samples_orig), &(args_info->min_num_interior_samples_given),
                &(local_args_info.min_num_interior_samples_given), optarg, 0, "10000", ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "min-num-interior-samples", '-',
                additional_error))
              goto failure;
          
          }
          /* Max time (in seconds) that the program is allowed to run.  If this time is reached, the computation will be stopped and the results computed so far will be displayed.  */
          else if (strcmp (long_options[option_index].name, "max-run-time") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->max_run_time_arg), 
                 &(args_info->max_run_time_orig), &(args_info->max_run_time_given),
                &(local_args_info.max_run_time_given), optarg, 0, 0, ARG_DOUBLE,
                check_ambiguity, override, 0, 0,
                "max-run-time", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of threads to use  (default=Number of logical cores).  */
          else if (strcmp (long_options[option_index].name, "num-threads") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->num_threads_arg), 
                 &(args_info->num_threads_orig), &(args_info->num_threads_given),
                &(local_args_info.num_threads_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "num-threads", '-',
                additional_error))
              goto failure;
          
          }
          /* Seed for the random number generator  (default=Randomly set).  */
          else if (strcmp (long_options[option_index].name, "seed") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->seed_arg), 
                 &(args_info->seed_orig), &(args_info->seed_given),
                &(local_args_info.seed_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "seed", '-',
                additional_error))
              goto failure;
          
          }
          /* Name of file for writing the surface points from Walk-on-Spheres.  */
          else if (strcmp (long_options[option_index].name, "surface-points-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->surface_points_file_arg), 
                 &(args_info->surface_points_file_orig), &(args_info->surface_points_file_given),
                &(local_args_info.surface_points_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "surface-points-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Name of file for writing the interior sample points.  */
          else if (strcmp (long_options[option_index].name, "interior-points-file") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->interior_points_file_arg), 
                 &(args_info->interior_points_file_orig), &(args_info->interior_points_file_given),
                &(local_args_info.interior_points_file_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "interior-points-file", '-',
                additional_error))
              goto failure;
          
          }
          /* Print statistics related to counts of hit points.  */
          else if (strcmp (long_options[option_index].name, "print-counts") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->print_counts_given),
                &(local_args_info.print_counts_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "print-counts", '-',
                additional_error))
              goto failure;
          
          }
          /* Print detailed RAM and timing information.  */
          else if (strcmp (long_options[option_index].name, "print-benchmarks") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->print_benchmarks_given),
                &(local_args_info.print_benchmarks_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "print-benchmarks", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of Monte Carlo steps to perform to compute a virial coefficient.  */
          else if (strcmp (long_options[option_index].name, "virial-steps") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->virial_steps_arg), 
                 &(args_info->virial_steps_orig), &(args_info->virial_steps_given),
                &(local_args_info.virial_steps_given), optarg, 0, 0, ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "virial-steps", '-',
                additional_error))
              goto failure;
          
          }
          /* Order of virial coefficient to compute.  */
          else if (strcmp (long_options[option_index].name, "virial-coefficient-order") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->virial_coefficient_order_arg), 
                 &(args_info->virial_coefficient_order_orig), &(args_info->virial_coefficient_order_given),
                &(local_args_info.virial_coefficient_order_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "virial-coefficient-order", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

#ifndef CONFIG_FILE_LINE_SIZE
#define CONFIG_FILE_LINE_SIZE 2048
#endif
#define ADDITIONAL_ERROR " in configuration file "

#define CONFIG_FILE_LINE_BUFFER_SIZE (CONFIG_FILE_LINE_SIZE+3)
/* 3 is for "--" and "=" */

static int
_cmdline_parser_configfile (const char *filename, int *my_argc)
{
  FILE* file;
  char my_argv[CONFIG_FILE_LINE_BUFFER_SIZE+1];
  char linebuf[CONFIG_FILE_LINE_SIZE];
  int line_num = 0;
  int result = 0, equal;
  char *fopt, *farg;
  char *str_index;
  size_t len, next_token;
  char delimiter;

  if ((file = fopen(filename, "r")) == 0)
    {
      fprintf (stderr, "%s: Error opening configuration file '%s'\n",
               CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  while ((fgets(linebuf, CONFIG_FILE_LINE_SIZE, file)) != 0)
    {
      ++line_num;
      my_argv[0] = '\0';
      len = strlen(linebuf);
      if (len > (CONFIG_FILE_LINE_BUFFER_SIZE-1))
        {
          fprintf (stderr, "%s:%s:%d: Line too long in configuration file\n",
                   CMDLINE_PARSER_PACKAGE, filename, line_num);
          result = EXIT_FAILURE;
          break;
        }

      /* find first non-whitespace character in the line */
      next_token = strspn (linebuf, " \t\r\n");
      str_index  = linebuf + next_token;

      if ( str_index[0] == '\0' || str_index[0] == '#')
        continue; /* empty line or comment line is skipped */

      fopt = str_index;

      /* truncate fopt at the end of the first non-valid character */
      next_token = strcspn (fopt, " \t\r\n=");

      if (fopt[next_token] == '\0') /* the line is over */
        {
          farg  = 0;
          equal = 0;
          goto noarg;
        }

      /* remember if equal sign is present */
      equal = (fopt[next_token] == '=');
      fopt[next_token++] = '\0';

      /* advance pointers to the next token after the end of fopt */
      next_token += strspn (fopt + next_token, " \t\r\n");

      /* check for the presence of equal sign, and if so, skip it */
      if ( !equal )
        if ((equal = (fopt[next_token] == '=')))
          {
            next_token++;
            next_token += strspn (fopt + next_token, " \t\r\n");
          }
      str_index  += next_token;

      /* find argument */
      farg = str_index;
      if ( farg[0] == '\"' || farg[0] == '\'' )
        { /* quoted argument */
          str_index = strchr (++farg, str_index[0] ); /* skip opening quote */
          if (! str_index)
            {
              fprintf
                (stderr,
                 "%s:%s:%d: unterminated string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }
      else
        { /* read up the remaining part up to a delimiter */
          next_token = strcspn (farg, " \t\r\n#\'\"");
          str_index += next_token;
        }

      /* truncate farg at the delimiter and store it for further check */
      delimiter = *str_index, *str_index++ = '\0';

      /* everything but comment is illegal at the end of line */
      if (delimiter != '\0' && delimiter != '#')
        {
          str_index += strspn(str_index, " \t\r\n");
          if (*str_index != '\0' && *str_index != '#')
            {
              fprintf
                (stderr,
                 "%s:%s:%d: malformed string in configuration file\n",
                 CMDLINE_PARSER_PACKAGE, filename, line_num);
              result = EXIT_FAILURE;
              break;
            }
        }

    noarg:
      if (!strcmp(fopt,"include")) {
        if (farg && *farg) {
          result = _cmdline_parser_configfile(farg, my_argc);
        } else {
          fprintf(stderr, "%s:%s:%d: include requires a filename argument.\n",
                  CMDLINE_PARSER_PACKAGE, filename, line_num);
        }
        continue;
      }
      len = strlen(fopt);
      strcat (my_argv, len > 1 ? "--" : "-");
      strcat (my_argv, fopt);
      if (len > 1 && ((farg && *farg) || equal))
        strcat (my_argv, "=");
      if (farg && *farg)
        strcat (my_argv, farg);
      ++(*my_argc);

      cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
      cmd_line_list_tmp->next = cmd_line_list;
      cmd_line_list = cmd_line_list_tmp;
      cmd_line_list->string_arg = gengetopt_strdup(my_argv);
    } /* while */

  if (file)
    fclose(file);
  return result;
}

int
cmdline_parser_configfile (
  const char *filename,
                           struct gengetopt_args_info *args_info,
                           int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;
  
  return cmdline_parser_config_file (filename, args_info, &params);
}

int
cmdline_parser_config_file (const char *filename,
                           struct gengetopt_args_info *args_info,
                           struct cmdline_parser_params *params)
{
  int i, result;
  int my_argc = 1;
  char **my_argv_arg;
  char *additional_error;

  /* store the program name */
  cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
  cmd_line_list_tmp->next = cmd_line_list;
  cmd_line_list = cmd_line_list_tmp;
  cmd_line_list->string_arg = gengetopt_strdup (CMDLINE_PARSER_PACKAGE);

  result = _cmdline_parser_configfile(filename, &my_argc);

  if (result != EXIT_FAILURE) {
    my_argv_arg = (char **) malloc((my_argc+1) * sizeof(char *));
    cmd_line_list_tmp = cmd_line_list;

    for (i = my_argc - 1; i >= 0; --i) {
      my_argv_arg[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

    my_argv_arg[my_argc] = 0;

    additional_error = (char *)malloc(strlen(filename) + strlen(ADDITIONAL_ERROR) + 1);
    strcpy (additional_error, ADDITIONAL_ERROR);
    strcat (additional_error, filename);
    result =
      cmdline_parser_internal (my_argc, my_argv_arg, args_info,
                              params,
                              additional_error);

    free (additional_error);
    free (my_argv_arg);
  }

  free_cmd_list();
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
