// Generated by Bisonc++ V6.01.00 on Wed, 12 Aug 2020 19:26:36 -0400

// base/comment

// $insert class.ih
#include "BodParser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {276, 0}, // 1: lines ->  <empty>
     {276, 2}, // 2: lines ->  lines line
     {277, 1}, // 3: line ->  sphereDef
     {277, 1}, // 4: line ->  cubeDef
     {277, 1}, // 5: line ->  cuboidDef
     {277, 1}, // 6: line ->  atomDef
     {277, 1}, // 7: line ->  voxelsFile
     {277, 1}, // 8: line ->  trajectoryFiles
     {277, 1}, // 9: line ->  parameter
     {278, 5}, // 10: sphereDef (SPHERE) ->  SPHERE real real real real
     {279, 5}, // 11: cubeDef (CUBE) ->  CUBE real real real real
     {280, 7}, // 12: cuboidDef (CUBOID) ->  CUBOID real real real real real real
     {281, 11}, // 13: atomDef (ATOM) ->  ATOM INT word word WORD INT real real real real real
     {281, 10}, // 14: atomDef (ATOM) ->  ATOM INT word word INT real real real real real
     {282, 2}, // 15: voxelsFile (VOXELS) ->  VOXELS word
     {283, 3}, // 16: trajectoryFiles (TRAJECTORY) ->  TRAJECTORY word word
     {284, 2}, // 17: parameter (ST) ->  ST real
     {284, 2}, // 18: parameter (RLAUNCH) ->  RLAUNCH real
     {284, 3}, // 19: parameter (HUNITS) ->  HUNITS real word
     {284, 2}, // 20: parameter (UNITS) ->  UNITS word
     {284, 3}, // 21: parameter (TEMP) ->  TEMP real word
     {284, 3}, // 22: parameter (MASS) ->  MASS real word
     {284, 3}, // 23: parameter (VISCOSITY) ->  VISCOSITY real word
     {284, 2}, // 24: parameter (BF) ->  BF real
     {285, 1}, // 25: real (FLOAT) ->  FLOAT
     {285, 1}, // 26: real (INT) ->  INT
     {286, 1}, // 27: word (WORD) ->  WORD
     {286, 1}, // 28: word (FLOAT) ->  FLOAT
     {286, 1}, // 29: word (INT) ->  INT
     {287, 1}, // 30: lines_$ ->  lines
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { DEF_RED}, {  2} },         
    { {     276}, {  1} }, // lines
    { {       0}, { -1} },         
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {       24} },                   
    { {       277}, {        2} }, // line           
    { {       278}, {        3} }, // sphereDef      
    { {       279}, {        4} }, // cubeDef        
    { {       280}, {        5} }, // cuboidDef      
    { {       281}, {        6} }, // atomDef        
    { {       282}, {        7} }, // voxelsFile     
    { {       283}, {        8} }, // trajectoryFiles
    { {       284}, {        9} }, // parameter      
    { {       259}, {       10} }, // SPHERE         
    { {       260}, {       11} }, // CUBE           
    { {       261}, {       12} }, // CUBOID         
    { {       262}, {       13} }, // ATOM           
    { {       263}, {       14} }, // VOXELS         
    { {       264}, {       15} }, // TRAJECTORY     
    { {       265}, {       16} }, // ST             
    { {       266}, {       17} }, // RLAUNCH        
    { {       267}, {       18} }, // HUNITS         
    { {       268}, {       19} }, // UNITS          
    { {       269}, {       20} }, // TEMP           
    { {       270}, {       21} }, // MASS           
    { {       271}, {       22} }, // VISCOSITY      
    { {       272}, {       23} }, // BF             
    { {     EOF__}, { ACCEPT__} },                   
    { {         0}, {        0} },                   
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_3[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_8[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 24} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 27} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 28} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       257}, { 29} }, // INT
    { {         0}, {  0} },       
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 30} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 34} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_16[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 35} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 36} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 37} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 38} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 39} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 40} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 41} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 42} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 43} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 44} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 45} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 46} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 47} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 48} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 49} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 50} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 51} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 52} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 53} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 54} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  5} },         
    { {       286}, { 55} }, // word 
    { {       273}, { 31} }, // WORD 
    { {       258}, { 32} }, // FLOAT
    { {       257}, { 33} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_49[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_50[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 56} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 57} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 58} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  3} },        
    { {       273}, { 59} }, // WORD
    { {       257}, { 60} }, // INT 
    { {         0}, {  0} },        
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 61} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       257}, { 62} }, // INT
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 63} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 64} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 65} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 66} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 67} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 68} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 69} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 70} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 71} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 72} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  4} },         
    { {       285}, { 73} }, // real 
    { {       258}, { 25} }, // FLOAT
    { {       257}, { 26} }, // INT  
    { {         0}, {  0} },         
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,
};

} // anonymous namespace ends


// $insert namespace-open
namespace bod_parser
{

// $insert polymorphicCode
namespace Meta__
{

size_t const *t_nErrors;
// $insert idoftag
char const *idOfTag__[] = {
    "STRING_TYPE",
    "FLOAT_TYPE",
    "<undefined>"
};

size_t const *s_nErrors__;

Base::~Base()
{}

}   // namespace Meta__

// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
BodParserBase::BodParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
    Meta__::t_nErrors = &d_nErrors__;
}

// base/clearin
void BodParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void BodParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void BodParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void BodParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int BodParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void BodParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void BodParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void BodParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void BodParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void BodParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void BodParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void BodParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void BodParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t BodParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void BodParser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void BodParser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 2:
#line 16 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(-1));
        }
        break;

        case 3:
#line 20 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 4:
#line 22 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 5:
#line 24 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 6:
#line 26 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 7:
#line 28 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 8:
#line 30 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 9:
#line 32 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
            d_val__ = std::move(vs__(0));
        }
        break;

        case 10:
#line 37 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addSphere(vs__(-3).get<Tag__::FLOAT_TYPE>(), vs__(-2).get<Tag__::FLOAT_TYPE>(), vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 11:
#line 45 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addCube(vs__(-3).get<Tag__::FLOAT_TYPE>(), vs__(-2).get<Tag__::FLOAT_TYPE>(), vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 12:
#line 53 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addCuboid(vs__(-5).get<Tag__::FLOAT_TYPE>(), vs__(-4).get<Tag__::FLOAT_TYPE>(), vs__(-3).get<Tag__::FLOAT_TYPE>(), vs__(-2).get<Tag__::FLOAT_TYPE>(), vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 13:
#line 61 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addSphere(vs__(-4).get<Tag__::FLOAT_TYPE>(), vs__(-3).get<Tag__::FLOAT_TYPE>(), vs__(-2).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 14:
#line 67 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addSphere(vs__(-4).get<Tag__::FLOAT_TYPE>(), vs__(-3).get<Tag__::FLOAT_TYPE>(), vs__(-2).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 15:
#line 74 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addVoxels(vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 16:
#line 81 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         addTrajectory(vs__(-1).get<Tag__::STRING_TYPE>(), vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 17:
#line 88 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setST(vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 18:
#line 93 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setRLAUNCH(vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 19:
#line 98 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setHUNITS(vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 20:
#line 103 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setUNITS(vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 21:
#line 108 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setTEMP(vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 22:
#line 113 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setMASS(vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 23:
#line 118 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setVISCOSITY(vs__(-1).get<Tag__::FLOAT_TYPE>(), vs__(0).get<Tag__::STRING_TYPE>());
         }
        break;

        case 24:
#line 123 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         setBF(vs__(0).get<Tag__::FLOAT_TYPE>());
         }
        break;

        case 25:
#line 130 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         d_val__ = stod(d_scanner.matched());
         }
        break;

        case 26:
#line 135 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         d_val__ = stod(d_scanner.matched());
         }
        break;

        case 27:
#line 142 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         d_val__ = d_scanner.matched();
         }
        break;

        case 28:
#line 147 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         d_val__ = d_scanner.matched();
         }
        break;

        case 29:
#line 152 "/home/dcj/Projects/zeno/cpp/zeno-cli/src/BodParser/bod_grammar"
        {
         d_val__ = d_scanner.matched();
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void BodParser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void BodParser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void BodParser::print__()
{
// $insert print
}

// derived/parse
int BodParser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail

// $insert namespace-close
}

