// Generated by Flexc++ V2.06.02 on Fri, 27 Sep 2019 14:45:50 -0400

#include <iostream>
#include <fstream>
#include <sstream>
#include <stdexcept>

// $insert class_ih
#include "BodScanner.ih"

// $insert namespace-open
namespace bod_parser
{

    // s_ranges__: use (unsigned) characters as index to obtain
    //           that character's range-number.
    //           The range for EOF is defined in a constant in the
    //           class header file
size_t const BodScannerBase::s_ranges__[] =
{
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
     4, 4, 4, 4, 4, 4, 4, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 8, 9,10,11,12,13,13,
    13,13,13,13,13,13,13,13,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,
    14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,15,16,17,
    18,19,20,21,22,23,24,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,39,39,
    39,39,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,
    40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,
    40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,
    40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,
    40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,
    40,40,40,40,40,40,
};

// $insert startcondinfo
    // s_dfa__ contains the rows of *all* DFAs ordered by start state.  The
    // enum class StartCondition__is defined in the baseclass header.
    // StartCondition__::INITIAL is always 0.  Each entry defines the row to
    // transit to if the column's character range was sensed. Row numbers are
    // relative to the used DFA, and d_dfaBase__ is set to the first row of
    // the subset to use.  The row's final two values are respectively the
    // rule that may be matched at this state, and the rule's FINAL flag. If
    // the final value equals FINAL (= 1) then, if there's no continuation,
    // the rule is matched. If the BOL flag (8) is also set (so FINAL + BOL (=
    // 9) is set) then the rule only matches when d_atBOL is also true.
int const BodScannerBase::s_dfa__[][44] =
{
    // INITIAL
    {-1, 1, 1, 1,-1, 1, 2, 2, 3, 2, 3, 4, 5, 6, 2, 7, 8, 9, 2, 2,
          2, 2,10, 2, 2, 2,11, 2, 2, 2, 2,12,13,14,15,16, 2, 2, 2, 2,
         -1,-1,    -1, -1},  // 0
    {-1, 1, 1, 1,-1, 1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,     2, -1},  // 1
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 2
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 4, 2, 6, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 3
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2,17, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 4
    {-1,-1,-1,-1,-1,-1, 2,18, 2, 2, 2, 2,19, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 5
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2,17, 2, 6, 2, 2, 2, 2, 2,20,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     3, -1},  // 6
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,21, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 7
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         22, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 8
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,23, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 9
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,24,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,25, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 10
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2,26, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 11
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2,27, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 12
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2,28, 2, 2, 2,29, 2, 2, 2, 2, 2, 2,
         -1,-1,     5, -1},  // 13
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,30,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 14
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2,31, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 15
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2,32, 2, 2, 2, 2,33, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 16
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2,17, 2, 2, 2, 2, 2,20,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     4, -1},  // 17
    {34,34,-1,34,34,34,18,35,18,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
         34,-1,    18, -1},  // 18
    {36,36,37,36,36,36,19,19,19,19,19,19,19,19,19,19,19,19,19,19,
         19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,
         36,-1,    18, -1},  // 19
    {-1,-1,-1,-1,-1,-1, 2, 2,38, 2,38, 2, 2,39, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 20
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2,40, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 21
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    17, -1},  // 22
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,41, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 23
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,42, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 24
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2,43, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 25
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,44, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 26
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2,45, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 27
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2,46, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 28
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    10, -1},  // 29
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2,47, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 30
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2,48, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 31
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,49, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 32
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,50, 2, 2,
         -1,-1,    18, -1},  // 33
    {34,34,-1,34,34,34,34,51,34,34,34,34,34,34,34,34,34,34,34,34,
         34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,
         34,-1,    -1, -1},  // 34
    {34,34,-1,34,34,34,18,35,18,18,18,18,52,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
         34,-1,    18, -1},  // 35
    {36,36,37,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,
         36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,
         36,-1,    -1, -1},  // 36
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,     1, -1},  // 37
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2,39, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 38
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2,39, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     4, -1},  // 39
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2,53, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 40
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,54,
          2, 2, 2, 2, 2, 2, 2, 2,55, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 41
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2,56, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 42
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2,57, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 43
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,58, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 44
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,59, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 45
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,60,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 46
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2,61, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 47
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,62, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 48
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,63, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 49
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,64,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 50
    {34,34,-1,34,34,34,34,51,34,34,34,34,65,34,34,34,34,34,34,34,
         34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,
         34,-1,    -1, -1},  // 51
    {34,34,-1,34,34,34,18,35,18,18,18,18,18,18,18,18,18,18,18,18,
         18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,
         34,-1,     0, -1},  // 52
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     8, -1},  // 53
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     6, -1},  // 54
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2,66, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 55
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,67, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 56
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,68, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 57
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    15, -1},  // 58
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2,69, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 59
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,70, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 60
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    14, -1},  // 61
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,71, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 62
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2,72, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 63
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2,73, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 64
    {34,34,-1,34,34,34,34,51,34,34,34,34,34,34,34,34,34,34,34,34,
         34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,
         34,-1,     0, -1},  // 65
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,74, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 66
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2,53, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 67
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,75, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 68
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,76, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 69
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,77,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 70
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    13, -1},  // 71
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,78, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 72
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,79, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 73
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     7, -1},  // 74
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    12, -1},  // 75
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2,80, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 76
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     5, -1},  // 77
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2,81, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 78
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,     9, -1},  // 79
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    11, -1},  // 80
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,82, 2, 2, 2, 2, 2, 2,
         -1,-1,    18, -1},  // 81
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,83, 2,
         -1,-1,    18, -1},  // 82
    {-1,-1,-1,-1,-1,-1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         -1,-1,    16, -1},  // 83
};


int const (*BodScannerBase::s_dfaBase__[])[44] =
{
    s_dfa__ + 0,
};

size_t BodScannerBase::s_istreamNr = 0;

// $insert inputImplementation
BodScannerBase::Input::Input()
:
    d_in(0),
    d_lineNr(1)
{}

BodScannerBase::Input::Input(std::istream *iStream, size_t lineNr)
:
    d_in(iStream),
    d_lineNr(lineNr)
{}

size_t BodScannerBase::Input::get()
{
    switch (size_t ch = next())         // get the next input char
    {
        case '\n':
            ++d_lineNr;
        // FALLING THROUGH

        default:
        return ch;
    }
}

size_t BodScannerBase::Input::next()
{
    size_t ch;

    if (d_deque.empty())                // deque empty: next char fm d_in
    {
        if (d_in == 0)
            return AT_EOF;
        ch = d_in->get();
        return *d_in ? ch : static_cast<size_t>(AT_EOF);
    }

    ch = d_deque.front();
    d_deque.pop_front();

    return ch;
}

void BodScannerBase::Input::reRead(size_t ch)
{
    if (ch < 0x100)
    {
        if (ch == '\n')
            --d_lineNr;
        d_deque.push_front(ch);
    }
}

void BodScannerBase::Input::reRead(std::string const &str, size_t fm)
{
    for (size_t idx = str.size(); idx-- > fm; )
        reRead(str[idx]);
}

BodScannerBase::BodScannerBase(std::istream &in, std::ostream &out)
:
    d_filename("-"),
    d_out(new std::ostream(out.rdbuf())),
// $insert interactiveInit
    d_in(0),
    d_input(new std::istream(in.rdbuf())),
    d_dfaBase__(s_dfa__)
{}

void BodScannerBase::switchStream__(std::istream &in, size_t lineNr)
{
    d_input.close();
    d_input = Input(new std::istream(in.rdbuf()), lineNr);
}


BodScannerBase::BodScannerBase(std::string const &infilename, std::string const &outfilename)
:
    d_filename(infilename),
    d_out(outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
          outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                  new std::ofstream(outfilename)),
    d_input(new std::ifstream(infilename)),
    d_dfaBase__(s_dfa__)
{}

void BodScannerBase::switchStreams(std::istream &in, std::ostream &out)
{
    switchStream__(in, 1);
    switchOstream(out);
}


void BodScannerBase::switchOstream(std::ostream &out)
{
    *d_out << std::flush;
    d_out.reset(new std::ostream(out.rdbuf()));
}

// $insert debugFunctions
void BodScannerBase::setDebug(bool onOff)
{}

bool BodScannerBase::debug() const
{
    return false;
}

void BodScannerBase::redo(size_t nChars)
{
    size_t from = nChars >= length() ? 0 : length() - nChars;
    d_input.reRead(d_matched, from);
    d_matched.resize(from);
}

void BodScannerBase::switchOstream(std::string const &outfilename)
{
    *d_out << std::flush;
    d_out.reset(
            outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
            outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                    new std::ofstream(outfilename));
}


void BodScannerBase::switchIstream(std::string const &infilename)
{
    d_input.close();
    d_filename = infilename;
    d_input = Input(new std::ifstream(infilename));
    d_atBOL = true;
}

void BodScannerBase::switchStreams(std::string const &infilename,
                           std::string const &outfilename)
{
    switchOstream(outfilename);
    switchIstream(infilename);
}

void BodScannerBase::pushStream(std::istream  &istr)
{
    std::istream *streamPtr = new std::istream(istr.rdbuf());
    p_pushStream("(istream)", streamPtr);
}

void BodScannerBase::pushStream(std::string const &name)
{
    std::istream *streamPtr = new std::ifstream(name);
    if (!*streamPtr)
    {
        delete streamPtr;
        throw std::runtime_error("Cannot read " + name);
    }
    p_pushStream(name, streamPtr);
}


void BodScannerBase::p_pushStream(std::string const &name, std::istream *streamPtr)
{
    if (d_streamStack.size() == s_maxSizeofStreamStack__)
    {
        delete streamPtr;
        throw std::length_error("Max stream stack size exceeded");
    }

    d_streamStack.push_back(StreamStruct{d_filename, d_input});
    d_filename = name;
    d_input = Input(streamPtr);
    d_atBOL = true;
}

bool BodScannerBase::popStream()
{
    d_input.close();

    if (d_streamStack.empty())
        return false;

    StreamStruct &top = d_streamStack.back();

    d_input =   top.pushedInput;
    d_filename = top.pushedName;
    d_streamStack.pop_back();

    return true;
}



  // See the manual's section `Run-time operations' section for an explanation
  // of this member.
BodScannerBase::ActionType__ BodScannerBase::actionType__(size_t range)
{
    d_nextState = d_dfaBase__[d_state][range];

    if (d_nextState != -1)                  // transition is possible
        return ActionType__::CONTINUE;

    if (knownFinalState())                  // FINAL state reached
        return ActionType__::MATCH;         

    if (d_matched.size())
        return ActionType__::ECHO_FIRST;    // no match, echo the 1st char

    return range != s_rangeOfEOF__ ? 
                ActionType__::ECHO_CH 
            : 
                ActionType__::RETURN;
}

void BodScannerBase::accept(size_t nChars)          // old name: less
{
    if (nChars < d_matched.size())
    {
        d_input.reRead(d_matched, nChars);
        d_matched.resize(nChars);
    }
}

void BodScannerBase::setMatchedSize(size_t length)
{
    d_input.reRead(d_matched, length);  // reread the tail section
    d_matched.resize(length);           // return what's left
}

  // At this point a rule has been matched.  The next character is not part of
  // the matched rule and is sent back to the input.  The final match length
  // is determined, the index of the matched rule is determined, and then
  // d_atBOL is updated. Finally the rule's index is returned.
  // The numbers behind the finalPtr assignments are explained in the 
  // manual's `Run-time operations' section.
size_t BodScannerBase::matched__(size_t ch)
{
    d_input.reRead(ch);

    FinalData *finalPtr;
                            
    if (not d_atBOL)                    // not at BOL
        finalPtr = &d_final.std;        // then use the std rule (3, 4)

                                        // at BOL
    else if (not available(d_final.std.rule))   // only a BOL rule avail.
            finalPtr = &d_final.bol;            // use the BOL rule (6)

    else if (not available(d_final.bol.rule)) // only a std rule is avail.
        finalPtr = &d_final.std;        // use the std rule (7)
        
    else if (                           // Both are available (8)
        d_final.bol.length !=           // check lengths of matched texts
        d_final.std.length              // unequal lengths, use the rule
    )                                   // having the longer match length
        finalPtr =              
            d_final.bol.length > d_final.std.length ?
                &d_final.bol
            :
                &d_final.std;

    else                            // lengths are equal: use 1st rule
        finalPtr = 
            d_final.bol.rule < d_final.std.rule ?
                &d_final.bol
            :
                &d_final.std;

    setMatchedSize(finalPtr->length);

    d_atBOL = d_matched.back() == '\n';


    return finalPtr->rule;
}

size_t BodScannerBase::getRange__(int ch)       // using int to prevent casts
{
// $insert caseCheck
    ch = tolower(ch);

    return ch == AT_EOF ? as<size_t>(s_rangeOfEOF__) : s_ranges__[ch];
}

  // At this point d_nextState contains the next state and continuation is
  // possible. The just read char. is appended to d_match
void BodScannerBase::continue__(int ch)
{
    d_state = d_nextState;

    if (ch != AT_EOF)
        d_matched += ch;
}

void BodScannerBase::echoCh__(size_t ch)
{
    *d_out << as<char>(ch);
    d_atBOL = ch == '\n';
}


   // At this point there is no continuation. The last character is
   // pushed back into the input stream as well as all but the first char. in
   // the buffer. The first char. in the buffer is echoed to stderr. 
   // If there isn't any 1st char yet then the current char doesn't fit any
   // rules and that char is then echoed
void BodScannerBase::echoFirst__(size_t ch)
{
    d_input.reRead(ch);
    d_input.reRead(d_matched, 1);
    echoCh__(d_matched[0]);
}

    // Update the rules associated with the current state, do this separately
    // for BOL and std rules.
    // If a rule was set, update the rule index and the current d_matched
    // length. 
void BodScannerBase::updateFinals__()
{
    size_t len = d_matched.size();

    int const *rf = d_dfaBase__[d_state] + s_finIdx__;

    if (rf[0] != -1)        // update to the latest std rule
    {
        d_final.std = FinalData { as<size_t>(rf[0]), len };
    }

    if (rf[1] != -1)        // update to the latest bol rule
    {
        d_final.bol = FinalData { as<size_t>(rf[1]), len };
    }
}

void BodScannerBase::reset__()
{
    d_final = Final{ 
                    FinalData{s_unavailable, 0}, 
                    FinalData {s_unavailable, 0} 
                };

    d_state = 0;
    d_return = true;

    if (!d_more)
        d_matched.clear();

    d_more = false;
}

int BodScanner::executeAction__(size_t ruleIdx)
try
{
    switch (ruleIdx)
    {
        // $insert actions
        case 3:
        {
#line 8 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::INT;
        }
        break;
        case 4:
        {
#line 9 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::FLOAT;
        }
        break;
        case 5:
        {
#line 10 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::SPHERE;
        }
        break;
        case 6:
        {
#line 11 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::CUBE;
        }
        break;
        case 7:
        {
#line 12 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::CUBOID;
        }
        break;
        case 8:
        {
#line 13 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::ATOM;
        }
        break;
        case 9:
        {
#line 14 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::VOXELS;
        }
        break;
        case 10:
        {
#line 15 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::ST;
        }
        break;
        case 11:
        {
#line 16 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::RLAUNCH;
        }
        break;
        case 12:
        {
#line 17 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::HUNITS;
        }
        break;
        case 13:
        {
#line 18 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::UNITS;
        }
        break;
        case 14:
        {
#line 19 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::TEMP;
        }
        break;
        case 15:
        {
#line 20 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::MASS;
        }
        break;
        case 16:
        {
#line 21 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::VISCOSITY;
        }
        break;
        case 17:
        {
#line 22 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::BF;
        }
        break;
        case 18:
        {
#line 23 "/home/dcj/Projects/zeno-release/cpp/src/BodParser/bod_lexer"
            return BodParser::STRING;
        }
        break;
    }
    noReturn__();
    return 0;
}
catch (Leave__ value)
{
    return static_cast<int>(value);
}

int BodScanner::lex__()
{
    reset__();
    preCode();

    while (true)
    {
        size_t ch = get__();                // fetch next char
        size_t range = getRange__(ch);      // determine the range

        updateFinals__();                    // update the state's Final info

        switch (actionType__(range))        // determine the action
        {
            case ActionType__::CONTINUE:
                continue__(ch);
            continue;

            case ActionType__::MATCH:
            {
                d_token__ = executeAction__(matched__(ch));
                if (return__())
                {
                    print();
                    postCode(PostEnum__::RETURN);
                    return d_token__;
                }
                break;
            }

            case ActionType__::ECHO_FIRST:
                echoFirst__(ch);
            break;

            case ActionType__::ECHO_CH:
                echoCh__(ch);
            break;

            case ActionType__::RETURN:
                if (!popStream())
                {
                     postCode(PostEnum__::END);
                     return 0;
                }
                postCode(PostEnum__::POP);
             continue;
        } // switch

        postCode(PostEnum__::WIP);

        reset__();
        preCode();
    } // while
}

void BodScannerBase::print__() const
{
}


// $insert namespace-close
}
